// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6acEpbQncVN3lsTjLxEJRVbFKe8xGi4',
    appId: '1:773805340670:web:5174397900c064a0cab2af',
    messagingSenderId: '773805340670',
    projectId: 'students-hub-c9fab',
    authDomain: 'students-hub-c9fab.firebaseapp.com',
    databaseURL: 'https://students-hub-c9fab-default-rtdb.firebaseio.com',
    storageBucket: 'students-hub-c9fab.firebasestorage.app',
    measurementId: 'G-EBZ489VFQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2siDCxei-FtnlCe5181tMhPD2PdPtwTM',
    appId: '1:773805340670:android:b2cf4a6ee229cb06cab2af',
    messagingSenderId: '773805340670',
    projectId: 'students-hub-c9fab',
    databaseURL: 'https://students-hub-c9fab-default-rtdb.firebaseio.com',
    storageBucket: 'students-hub-c9fab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDydKS-oEzUYiHXbwU7eM4Z3a7HVzB_azQ',
    appId: '1:773805340670:ios:c89c062623909759cab2af',
    messagingSenderId: '773805340670',
    projectId: 'students-hub-c9fab',
    databaseURL: 'https://students-hub-c9fab-default-rtdb.firebaseio.com',
    storageBucket: 'students-hub-c9fab.firebasestorage.app',
    iosBundleId: 'com.example.studenthubChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDydKS-oEzUYiHXbwU7eM4Z3a7HVzB_azQ',
    appId: '1:773805340670:ios:c89c062623909759cab2af',
    messagingSenderId: '773805340670',
    projectId: 'students-hub-c9fab',
    databaseURL: 'https://students-hub-c9fab-default-rtdb.firebaseio.com',
    storageBucket: 'students-hub-c9fab.firebasestorage.app',
    iosBundleId: 'com.example.studenthubChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO6acEpbQncVN3lsTjLxEJRVbFKe8xGi4',
    appId: '1:773805340670:web:cfba5d239870abd0cab2af',
    messagingSenderId: '773805340670',
    projectId: 'students-hub-c9fab',
    authDomain: 'students-hub-c9fab.firebaseapp.com',
    databaseURL: 'https://students-hub-c9fab-default-rtdb.firebaseio.com',
    storageBucket: 'students-hub-c9fab.firebasestorage.app',
    measurementId: 'G-MB0ZB1Z42B',
  );

}